apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.deployment.deploymentName }}
  namespace: {{ .Values.namespace }}
spec:
  replicas: {{ .Values.deployment.replicas }}
  selector:
    matchLabels:
      app: {{ .Values.app.appName }}
  template:
    metadata:
      labels:
        app: {{ .Values.app.appName }}
    spec:
      containers:
        - name: {{ .Values.deployment.containerName }}
          image: "{{ .Values.deployment.image }}:{{ .Values.version }}"
          ports:
            - containerPort: 8080
          env:
            - name: DATABASE_URL
              value: {{ .Values.deployment.env.databaseUrl }}
            - name: DATABASE_SHEMA
              value: {{ .Values.deployment.env.databaseShema }}
            - name: POSTGRES_USER
              value: {{ .Values.deployment.env.databaseUser }}
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.secret }}
                  key: dbPassword
      imagePullSecrets:
        - name: {{ .Values.pullSecret }}
