apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.service.serviceName }}
  namespace: {{ .Values.namespace }}
spec:
  selector:
    app: {{ .Values.app.appName }}
  ports:
    - name: {{ .Values.app.appName }}
      protocol: TCP
      port: 8080
      targetPort: 8080
  type: ClusterIP
