apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.service.service-name }}
  namespace: {{ .Values.namespace }}
spec:
  selector:
    app: {{ .Values.app.app-name }}
  ports:
    - name: {{ .Values.app.app-name }}
      protocol: TCP
      port: 8080
      targetPort: 8080
  type: ClusterIP
